### ISSUE TITLE
README : configuration part

### ISSUE THREAD

**Issue by adyb0** [Zaista/cypress-mysql#2]
How to configure this plugin on cypress 12/13 ? 

Configuring plugins via cypress/plugins/index.js is no longer supported as of Cypress version 10.0.0.

We recommend that you update your configuration. Please see the [plugins guide](https://docs.cypress.io/guides/tooling/plugins-guide) and the [migration guide](https://docs.cypress.io/guides/references/migration-guide) for more information on how to update your configuration.

**Comment by Zaista** [comment]
Alright. I can take care of it.
Who's `we`?

**Comment by adyb0** [comment]
Thanks for your help. It's work fine.

The part below was a copy-paste from the Cypress documentation, so "we" refers to the Cypress developers.
